### ISSUE TITLE
Support nested fields

### ISSUE THREAD

**Issue by ralphilius** [svrooij/rest-api-filter-fields#1]
Hello,

Is there anyway we can support nested fields like `title.rendered`? It will be helpful for associated media files.

**Comment by dimkasta** [comment]
This would be nice. Especially if there could be support for the &_embed option which offers additional object _embedded that contains the direct link of the featured image and so many other things
But I  guess somehow this object is considered private and is not returned in your $filtered_data array?

**Comment by xpluscal** [comment]
+1
This is especially needed when using Custom Fields plugins like acf and their apis, since there is much data stored in this nested field.

**Comment by svrooij** [comment]
good point.... will try to implement.

**Comment by bonsak** [comment]
Thanks for a great plugin.
acf.mytaxonomy returns the whole taxonomy object. But if i try acf.mytaxonomy.name or acf.mytaxonomy.term_id etc i get an error 500. Would it be possible to support deeper nesting than one level?

**Comment by svrooij** [comment]
@bonsak since the latest version it also has support for collections. A custom taxonomy sounds like a collection.
Could you check if In't works if you use `acf.mytaxonomy.first.name` The code responsible for extracting arrays is [here](https://github.com/svrooij/rest-api-filter-fields/blob/master/rest-api-filter-fields/includes/class-rest-api-filter-fields.php#L152).

I'm sure this code could be more efficient, but I don't know how. Happy to accept a pull request on this part.

**Comment by goryoatgit** [comment]
Great Plugin !!, 

I'm trying to implement it to get the afc.gallery.url only but it seems like its not working.
www.site.com/wp-json/wp/v2/pages?slug=page-slot?&fields=id,acf.gallery.url and only returns the id property.
