### ISSUE TITLE
Support for Menus?

### ISSUE THREAD

**Issue by ChrisSargent** [svrooij/rest-api-filter-fields#10]
Hi There,

Is it possible to support filtering menu fields too please?

Thanks,

Chris

**Comment by svrooij** [comment]
Chris could you explain what you mean with menu fields?
Do you have a working API running, and could you supply an URL?

**Comment by ChrisSargent** [comment]
Hi, yeah, sorry I forgot this wasn't core, it's from a plugin that provides a menus endpoint: https://en-gb.wordpress.org/plugins/wp-api-menus/

A couple of example URLs:
Menu list - http://www.travelaer.com/wp-json/wp-api-menus/v2/menu-locations/
Specific Menu - http://www.travelaer.com/wp-json/wp-api-menus/v2/menu-locations/primary

I'm only using the specific endpoint just now.

Thanks!

**Comment by svrooij** [comment]
It seems that the plugin you're using doesn't support modifying the response. The wp-api-menus will have to be modified to support it.
The user controller is doing it like [this](https://core.trac.wordpress.org/browser/tags/4.7/src/wp-includes/rest-api/endpoints/class-wp-rest-users-controller.php#L897)

So when returning the menu the initial plugin should do something like `return apply_filters( 'rest_prepare_menu', $response, $menu, $request );`

**Comment by ChrisSargent** [comment]
okay - I've opened a issue with the author of that plugin: https://github.com/unfulvio/wp-api-menus/issues/43

**Comment by krishnarajsinh** [comment]
How to Hide Certain Categories from the App that uses wp rest api for fetching the wordpress website posts. I want to hide particular categories post to be hide.

Please help me.

**Comment by svrooij** [comment]
I'm closing this issue because this plugin is no longer needed in Wordpress.
See https://github.com/svrooij/rest-api-filter-fields#deprecated for more details. Or check out the official [_fields](https://developer.wordpress.org/rest-api/using-the-rest-api/global-parameters/#_fields) parameter supported by the wordpress core.

I hope you enjoyed using this plugin, you might want to consider [sponsoring](https://github.com/sponsors/svrooij)
