### ISSUE TITLE
Support acf nested fields

### ISSUE THREAD

**Issue by gerryascn** [svrooij/rest-api-filter-fields#15]
Great Plugin !!,

I'm trying to implement it to get the afc.gallery.url only but it seems like its not working.
www.site.com/wp-json/wp/v2/pages?slug=page-slot?&fields=id,acf.gallery.url and only returns the id property.

@svrooij

**Comment by svrooij** [comment]
Are you sure the gallery is api there to begin with?

**Comment by stackprogramer** [comment]
i too when i tested nested features for wordpress it only returns title..........

https://blog.stackprogramer.xyz/wp-json/wp/v2/posts?fields=title.rendered

**Comment by kadamwhite** [comment]
It won’t handle nesting but the REST API now natively supports a ?_fields= parameter which accepts a comma-separated list

**Comment by svrooij** [comment]
I'm closing this issue because this plugin is no longer needed in Wordpress.
See https://github.com/svrooij/rest-api-filter-fields#deprecated for more details. Or check out the official [_fields](https://developer.wordpress.org/rest-api/using-the-rest-api/global-parameters/#_fields) parameter supported by the wordpress core.

I hope you enjoyed using this plugin, you might want to consider [sponsoring](https://github.com/sponsors/svrooij)
