### ISSUE TITLE
when i tested rest-api filter plugin on localhost website it can not work.

### ISSUE THREAD

**Issue by stackprogramer** [svrooij/rest-api-filter-fields#16]
My wordpress website url is http://localhost/wp/. when i want to using this plugin all rest api field return all field not filter of themand it doesn't work correctly, 

while for domain website like https://blog.stackprogramer.xyz/ it works like charm.
https://blog.stackprogramer.xyz/wp-json/wp/v2/posts?fields=id,title,content,link,excerpt,better_featured_image

an other person reported this issue on [this link](https://wordpress.stackexchange.com/questions/204686/wp-rest-api-v2-filters-doesnt-workl). what we can do for solving it, in future update it will be fixed?

**Comment by svrooij** [comment]
What is the problem? The link you’re referring to is totally unrelated.

**Comment by stackprogramer** [comment]
@svrooij on localhost/mywebsite  the your plugin filter dosn't work, it return all fields instead returning selected fields.

**Comment by svrooij** [comment]
I'm closing this issue because this plugin is no longer needed in Wordpress.
See https://github.com/svrooij/rest-api-filter-fields#deprecated for more details. Or check out the official [_fields](https://developer.wordpress.org/rest-api/using-the-rest-api/global-parameters/#_fields) parameter supported by the wordpress core.

I hope you enjoyed using this plugin, you might want to consider [sponsoring](https://github.com/sponsors/svrooij)
