### ISSUE TITLE
add custom fields 

### ISSUE THREAD

**Issue by abdallahmaali** [svrooij/rest-api-filter-fields#17]
Thanks for this amazing plugin, can I know how i can add custom fields to the response

**Comment by svrooij** [comment]
I'm closing this issue because this plugin is no longer needed in Wordpress.
See https://github.com/svrooij/rest-api-filter-fields#deprecated for more details. Or check out the official [_fields](https://developer.wordpress.org/rest-api/using-the-rest-api/global-parameters/#_fields) parameter supported by the wordpress core.

I hope you enjoyed using this plugin, you might want to consider [sponsoring](https://github.com/sponsors/svrooij)
