### ISSUE TITLE
filtering not working with fields containing ":"

### ISSUE THREAD

**Issue by mohamedbelhassen** [svrooij/rest-api-filter-fields#18]
I really appreciated this plugin.
But, I noticed that filtering fails when the field name contains  colon (:) such as the following wordpress fgields: wp:featuredmedia and wp:attachment

"wp:featuredmedia": [
{
"embeddable": true,
"href": "http://fahamni.tn/wp-json/wp/v2/media/76"
}
],
"wp:attachment": [
{
"href": "http://fahamni.tn/wp-json/wp/v2/media?parent=75"
}
],

could you please correct this bug or tell me how to proceed

**Comment by svrooij** [comment]
I'm closing this issue because this plugin is no longer needed in Wordpress.
See https://github.com/svrooij/rest-api-filter-fields#deprecated for more details. Or check out the official [_fields](https://developer.wordpress.org/rest-api/using-the-rest-api/global-parameters/#_fields) parameter supported by the wordpress core.

I hope you enjoyed using this plugin, you might want to consider [sponsoring](https://github.com/sponsors/svrooij)
