### ISSUE TITLE
return name form jsonobject

### ISSUE THREAD

**Issue by Poniyo** [svrooij/rest-api-filter-fields#20]
hi
i can return , ( name ) form json:
what to do?

"locations": {
      "listing_location": [
        {
          "term_id": 76,
          "name": "Amsterdam",
          "slug": "amsterdam",
        }

thanks

**Comment by svrooij** [comment]
I'm closing this issue because this plugin is no longer needed in Wordpress.
See https://github.com/svrooij/rest-api-filter-fields#deprecated for more details. Or check out the official [_fields](https://developer.wordpress.org/rest-api/using-the-rest-api/global-parameters/#_fields) parameter supported by the wordpress core.

I hope you enjoyed using this plugin, you might want to consider [sponsoring](https://github.com/sponsors/svrooij)
